name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          # php-version: 8.4
          php-version: 8.3 # Versão suportada pelo GitHub Actions
          tools: composer:v2
          # coverage: xdebug
          coverage: xdebug → none	# Evita sobrecarga desnecessária

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Publish Ziggy Configuration
        run: php artisan ziggy:generate

      - name: Build Assets
        #run: npm run build
        run: vite build --config vite.config.ts # ✅ força leitura correta do app.ts
        
      # - name: Tests Evita erro até que o Pest ou PHPUnit esteja pronto
      #  run: ./vendor/bin/pest
